### ISSUE TITLE
Where is the "custom hcitool-duration binary"?

### ISSUE THREAD

**Issue by vk2sky** [RadiusNetworks/radbeacon-gem#10]
README.md refers to a "custom hcitool-duration binary that adds a duration option to the hcitool lescan command". Where is this binary file located please?

**Comment by jnebeker** [comment]
I just posted the hcitool source with the duration option [here](https://github.com/RadiusNetworks/bluez/blob/hcitool-duration/tools/hcitool.c), it's a fork of BlueZ.  You should be able to compile it on your machine to create the binary used by the gem.

**Comment by vk2sky** [comment]
Great, thanks very much for that!
