### ISSUE TITLE
fetch undefined method error

### ISSUE THREAD

**Issue by jpurple** [RadiusNetworks/radbeacon-gem#14]
Error during fetch:

Here is a sample use of your gem in a file I call test.rb:

```ruby
require "radbeacon"
scanner = Radbeacon::Scanner.new(4)
radbeacon = scanner.fetch("00:07:80:C6:1D:B6")
radbeacon.dev_name = "Test Beacon"
radbeacon.uuid = "2F234454-CF6D-4A0F-ADF2-F4911BA9ABCD"
radbeacon.save("00000000")
```

I clone, build, and install the gemspec, and run the above test code by entering this into the terminal:

```bash
sudo gem build radbeacon.gemspec && \
  sudo gem install radbeacon-0.1.3.gem && \
  sudo hciconfig hci0 down && \
  sudo hciconfig hci0 up && \
  sudo ruby ../provisioning/test.rb
```

_Note that:_

a.)`sudo hciconfig hci0 down && sudo hciconfig hci0 up` _is done to avoid receiving a connection error_

_b.)  I do the build and install fresh with the above command because I was tracing the through the code and adding some output statements to analyze why it is not working_

Anyway, so the purpose of this message is that when I run a fetch using a mac address of a usb radbeacon I receive the following output in the terminal:

```
WARNING:  no description specified
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: radbeacon
  Version: 0.1.3
  File: radbeacon-0.1.3.gem
Successfully installed radbeacon-0.1.3
Parsing documentation for radbeacon-0.1.3
Done installing documentation for radbeacon after 1 seconds
1 gem installed
00:07:80:C6:1D:B6../provisioning/purple.rb:4:in `<main>': undefined method `dev_name=' for nil:NilClass (NoMethodError)
```

Note that the output regarding no description specified, successfully built, etc. is from the build process. The purpose of this issue is found in the last line about undefined method for `nil`. It seems that a `Radbeacon::Usb` object **IS** being returned (because if i print out `radbeacon.inspect` I can see this info:

`#<Radbeacon::BluetoothLeDevice:0xd2b130 @errors=[], @mac_address="00:07:80:C6:1D:B5", @name=nil, @is_connectable=false, @characteristics=[], @values={}>`

So the object is returned, but the `dev_name`, `major`, `minor`, etc. are not. One interesting thing is that I can put in a false mac address, and that will return a similar object.

_For perspective:_

`sudo hcitool lescan` works when I use it directly in the terminal. I can see the results of the scan. 

The beacon in question appears as:
`00:07:80:C6:1D:B6 RBUSB`

Also the following successfully produces a listing of nearby beacons:

```ruby
scanner = Radbeacon::Scanner.new(4)
radbeacon = scanner.fetch
```

**RECAP TL/DR:**

So the issue here is that I am following your documentation which indicates 

**There is also a fetch method that returns a Radbeacon::Usb object for a given MAC address.
radbeacon = scanner.fetch("11:22:33:44:55:66")**

And when I do, the following error occurs:

`00:07:80:C6:1D:B6../provisioning/test.rb:4:in '<main>': undefined method 'dev_name=' for nil:NilClass (NoMethodError)`

Please advise, thank you

**Comment by jpurple** [comment]
The issue appears to be here:

```

    def self.create_if_valid(device)
      print("\ninside create_if_valid\n")
      # Check everything
      required_attrs = [GATT_DEV_MODEL, GATT_DEV_ID, GATT_FWVERSION, GATT_DEV_NAME,
        GATT_UUID, GATT_MAJOR, GATT_MINOR, GATT_POWER, GATT_TXPOWER, GATT_INTERVAL, GATT_BCTYPE]
      if required_attrs.all? { |key| device.values[key] }
        print("\nrequired attributes were all present. new device created.\n")
        self.new(device)
      end
    end
```

A new beacon does not return the required attributes, and the code does not create them for us.

**Comment by jnebeker** [comment]
Do you happen to know what firmware version your RadBeacon USB is?  I believe this gem is only compatible with version 2.2 (circa 2015), it hasn't been updated to handle the latest firmware (v3.X).  

If you'd like you can downgrade the firmware of your USB to version 2.2 using the RadBeacon app for macOS, here's an article that describes that process:

https://radiusnetworks.zendesk.com/hc/en-us/articles/203351984-How-do-I-update-the-Firmware-of-a-RadBeacon-USB-

**Comment by jpurple** [comment]
Thanks James!

I have just now followed your advice to downgrade the firmware to 2.2.2, but still no success so I have brought it back to 3.2.3.  I would like to share that I have moved past the above documented issue.  Now I am at another place. To keep this message nice and short, I will get right to where we are now.  If I capture the output of the script to gattool, I can come up with my own set of commands.

So I can use gatttool like this:

```
gatttool -b 00:07:80:C6:1D:B6 --interactive
connect
char-write-req 0x001d 5465737420426561636f6e
char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0893E
```

It is on that last line (for 0x0020) that I receive this error:
```
/var/lib/gems/2.1.0/gems/radbeacon-0.1.3/lib/radbeacon/utils.rb:17:in `bytes_to_uuid': undefined method `delete' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.1.0/gems/radbeacon-0.1.3/lib/radbeacon/usb.rb:73:in `initialize'
	from ../provisioning/purple.rb:10:in `new'
	from ../provisioning/purple.rb:10:in `<main>'

```

So it seems there is an issue with uuid length being written? It appears to be nil? My script where I use radbeacon is simply:

```
require "radbeacon"
scanner = Radbeacon::Scanner.new(4)

newLe = Radbeacon::BluetoothLeDevice.new("00:07:80:C6:1D:B6", "Testing A Name")
newUSB = Radbeacon::Usb.new(newLe)

newUSB.dev_name = "Test Beacon"
newUSB.uuid = "F7826DA6-4FA2-4E98-8024-BC5B71E0893E"
newUSB.major = 5511
newUSB.minor = 8787
newUSB.power = -66
newUSB.tx_power = 3
newUSB.adv_rate = 10
newUSB.beacon_type = "dual"
newUSB.save('00000000')
print("after changes:\n")
print(newUSB.inspect)
print("\n\n")
```

**Comment by jnebeker** [comment]
Yeah it appears the UUID of the `newUSB` object is `nil` after creating it with the `newLe` object.  Can you check the value of `newUSB.uuid` after creating that object (line 4 in your script)?  It would also be helpful to check the value of `newLe.values["0x0020"]` to see if the UUID characteristic is missing from the `BluetoothLeDevice`.

**Comment by jpurple** [comment]
Thanks, great idea. I have printed the output by adding print statements like this:

```
newUSB.dev_name = "Test Beacon"
print("\ndev name test: " + newUSB.dev_name)

newUSB.uuid = "F7826DA6-4FA2-4E98-8024-BC5B71E0893E"
print("\nuuid test: " + newUSB.uuid)
```

and the output is

```
dev name test: Test Beacon
uuid test: F7826DA6-4FA2-4E98-8024-BC5B71E0893E
```

So at least right there, the values are not nil.  They don't appear to be nil elsewhere in the script either. I did a test to confirm this. In order to allow the script to continue, I went to utils.rb which contains the failing part:

```
def bytes_to_uuid(bytes)
      bytes.delete(' ').sub(/([a-fA-F0-9]{8})([a-fA-F0-9]{4})([a-fA-F0-9]{4})([a-fA-F0-9]{4})([a-fA-F0-9]{12})/, '\1-\2-\3-\4-\5').upcase
    end
```


and since the failure is due to nil, I have temporarily added "if bytes" to test for nil:
```
def bytes_to_uuid(bytes)
      bytes.delete(' ').sub(/([a-fA-F0-9]{8})([a-fA-F0-9]{4})([a-fA-F0-9]{4})([a-fA-F0-9]{4})([a-fA-F0-9]{12})/, '\1-\2-\3-\4-\5').upcase if bytes
    end
```

By doing that, the script proceeds to run further and in the process I have a chance to print out newUSB.inspect:

`#<Radbeacon::Usb:0x399d80 @errors=["Action failed: char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0893E"], @mac_address="00:07:80:C6:1D:B5", @dev_model=nil, @dev_id=nil, @dev_version=nil, @dev_name="Test Beacon", @uuid="F7826DA6-4FA2-4E98-8024-BC5B71E0893E", @major=5511, @minor=8787, @power=-66, @tx_power=3, @adv_rate=10, @beacon_type="dual">`

We see the uuid has made it in there.

Going one step further, I found the array of commands being sent to gatttool in this block of code which is in usb.rb:

```
update_params_commands = ["#{GATT_DEV_NAME} #{text_to_bytes(@dev_name)}",
          "#{GATT_UUID} #{uuid_to_bytes(@uuid)}", "#{GATT_MAJOR} #{major_minor_to_bytes(@major)}",
          "#{GATT_MINOR} #{major_minor_to_bytes(@minor)}", "#{GATT_POWER} #{power_to_bytes(@power)}",
          "#{GATT_TXPOWER} #{TRANSMIT_POWER_VALUES[@tx_power]}", "#{GATT_INTERVAL} #{ADVERTISING_RATE_VALUES[@adv_rate]}",
          "#{GATT_BCTYPE} #{BEACON_TYPES[@beacon_type]}", "#{GATT_ACTION} #{GATT_ACTION_UPDATE_ADV}", "#{GATT_PIN} #{pin_to_bytes(pin)}"]
```

and I removed the UUID command.

Meaning I just removed this:
`"#{GATT_UUID} #{uuid_to_bytes(@uuid)}",`

I did this just to see if other commands would run. Sure enough all other commands ran except the last command for action to save it.  So, I printed out the ruby script's gatttool output and the following statements are the same thing being output by your ruby script:

```
gatttool -b 00:07:80:C6:1D:B5 --interactive

connect

char-write-req 0x001d 5465737420426561636f6e

char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0893E
#problem

char-write-req 0x0023 1587

char-write-req 0x0026 2253

char-write-req 0x0029 be

char-write-req 0x002c 0f

char-write-req 0x002f 8000

char-write-req 0x003e 03

char-write-req 0x0038 00000001
#problem
```

only the above lines with "problem" don't work. 

Specifically they are:
**char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0893E
char-write-req 0x0038 00000001**

What would you do next? Thanks!

**Comment by jpurple** [comment]
(I half wonder... working backwards... starting with the above direct gatttool commands, what is wrong with THEM? Maybe that could then give insight into the code that produced them...)

**Comment by jnebeker** [comment]
Right, it's possible that those characteristics (0x0020 & 0x0038) aren't used in the newer firmware.  You should be able to interrogate the device to see what all of its characteristics are, with `gatttool` I believe you can run a `characteristics` command in interactive mode to discover all the characteristics of the device.  Can you try that and see if those characteristics are present?

**Comment by jpurple** [comment]
Very interesting!  (Well to me, as an iOS developer plowing into Ruby to get this script running it is interesting...) :)

I found these two items pertaining to 0x0020 & 0x0038 when I ran characteristics:
```
handle: 0x001f, char properties: 0x0a, char value handle: 0x0020, uuid: 0000aaa7-0000-1000-8000-00805f9b34fb

handle: 0x0037, char properties: 0x0a, char value handle: 0x0038, uuid: 0000aab7-0000-1000-8000-00805f9b34fb
```

In usb.rb, the lines corresponding to these are:

```
GATT_UUID          = "0x0020"
GATT_ACTION        = "0x0038"
```

So uuid and action. I have downgraded the firmware to 2.2.2 and experienced the same issue. It seems we are left with why these two commands (and only these two commands) are not successful but the rest are:

**char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0893E
char-write-req 0x0038 00000001**

0x0020 corresponds to device uuid, and 0x0038 corresponds to action.

**Comment by jnebeker** [comment]
Ok, I did some research and those characteristics are deprecated on 3.2.3 firmware so that explains why the commands fail in that case.

On version 2.2 (not sure about 2.2.2), I was able to connect to and update the major/tx_power of my USB with the gem.  Here are the commands I used:

```
radbeacon = Radbeacon::Scanner.new(10).fetch("00:07:80:15:74:5b")
radbeacon.major = 1
radbeacon.tx_power = 3
radbeacon.save("0000")
```

Can you try downgrading to 2.2 and using this code?

**Comment by jpurple** [comment]
Very nice!  The most significant item in your sample code is that you used lower case characters in the Mac address. Here is the line from your sample:
`radbeacon = Radbeacon::Scanner.new(10).fetch("00:07:80:15:74:5b")`

We were using upper case. Here is our line:
`newLe = Radbeacon::BluetoothLeDevice.new("00:07:80:C6:1D:B5", "A test name")`

By changing our Mac address to our lower case as well, the ruby script worked. We understand Mac addresses are generally lower case, but we had seen validation in the code for UUID and presumed similar validation existed for Mac address. Our attention was directed to UUID because that is where the problem was being encountered.

**Following this: WHAT DO WE DO FOR 3.2.3+?**
As instructed, we downgraded the firmware to 2.2.2 in order to run this, and it was successful. When we upgraded it, and tried to run it on 3.2.3, it failed with this error:

`@errors=["Action failed: char-write-req 0x0020 F7826DA64FA24E988024BC5B71E0894C"]`

We accept that 0x0020 has been deprecated in 3.2.3, and we are wondering then: what is the way to change the device UUID in 3.2.3?  Is there another register akin to 0x0020?

Our specific use case for this (ultimately awesome!) ruby script involves us setting up new beacons. So... if we need to use another tool (such as the RadBeacon MacOS app) to change the device UUID, or to first downgrade the firmware, it contradicts our aim of using this script.  I am hoping it is as simple as using something different than 0x0020 such as another register.

Thanks again!
Jack

**Comment by jnebeker** [comment]
Ok glad you got it working for the older firmware at least.

Version 3.2.3+ was a pretty major overhaul of the GATT characteristic structure, so unfortunately it's not as simple as reassigning the UUID to a different characteristic.  Essentially, instead of the beacon's identifiers (UUID, major, minor, etc.) being assigned to individual GATT characteristics, the beacon's entire Bluetooth advertisement PDU is assigned as a characteristic containing its raw bytes.  This way, the beacon can support any Bluetooth LE Advertisement and isn't limited to specific BLE beacon specs.  It's now up to whatever is configuring the beacon over GATT to build the advertisement PDU (based on the desired beacon spec and specific identifiers) and then assign that PDU to the beacon via GATT.  The RadBeacon firmware supports up to 5 different advertisements that each have a different GATT characteristic, here's the full list:

```
0x0047 # PDU 1
0x004a # PDU 2
0x004d # PDU 3
0x0050 # PDU 4
0x0053 # PDU 5
```

You can see these PDU GATT characteristics yourself if you query them with `gatttool`.  Or you can use the `radbeacon` gem  as follows to get the characteristics of the device:

```ruby
radbeacon = Radbeacon::BluetoothLeDevice.new("00:07:80:15:88:d8", "Radbeacon v3.2.3")
radbeacon.fetch_characteristics
puts radbeacon.values
```

That will output each GATT characteristic of the device and the corresponding value.  So for example, the first PDU of my RadBeacon v3.2.3 looks like this:

```
02 01 06 1b ff 18 01 be ac 2f 23 44 54 cf 6d 4a 0f ad f2 f4 91 1b a9 ff a6 00 01 00 02 be 00
```

Which corresponds to an AltBeacon advertisement with the following identifiers:

UUID (bytes 10-25): **2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6**
Major (bytes 26-27): **1**
Minor (bytes 28-29): **2**
TX Power (byte 30): **-66**

---

Because this is such a major change and would require a large amount of development work on this gem, we don't have any plans at this time to work on adding v3.2.3+ support.  That said, we'd be happy to provide you with any information you need if you'd like to build this functionality for yourself.

I'd also like to recommend our command line tool for communicating with RadBeacon USB devices over the USB port, called `rbcom`.  It requires a USB connection to the beacon, but it supports all versions of RadBeacon USB firmware (including v3.2.3).  If your use case doesn't require over-the-air communication, I'd strongly recommend switching to this approach.

You can install `rbcom` with Homebrew if you have a Mac:

```
# brew install radiusnetworks/utils/rbcom
```

**Comment by jpurple** [comment]
Thank you, James. This reply is extremely informative and helpful.  Not only does it tell us "what," it also helps us to understand "why." It is greatly appreciated.

Okay, so...

while it was a worthwhile endeavor on several levels for us to explore the over the air functionality, yes - going forward we will use the USB solution.

The questions we have now are:

a.) rbcom seems to be Mac only? I use Mac and that is fine with me! Although we were wondering if this is a Linux tool as well, or is there a Linux equivalent produced by you guys. We searched on your github and didn't find any.

b.) It sounds like instead of just setting the UUID, instead we need to take uuid, major, minor, and tx power, and join their bits together to form the beacon's entire Bluetooth advertisement PDU (which is assigned as a characteristic containing its raw bytes.) Once we have created that, can we use your tool rbcom to assign this to the beacon or do we need to use gatttool.  If so, what role does rbcom play for us, if any? (Bearing in mind that our main context for undertaking this project is to facilitate the configuration of new beacons.)  

For context: We have installed and executed rbcom in order to see available commands, which include:  **advoff, advrate, bctype, connper, connwin, frameN, privacy, reboot, tlmratio, tlmtype.**  At a glance, none of these seem to be the commands which change the advertisement PDU. That is why we are wondering if rbcom can play a part for us, or are we need to be using gatttool directly.

Thanks.

**Comment by csexton** [comment]
Hey @jpurple, I help maintain `rbcom`. We are open to sharing a linux build if you need it, but don't currently distribute the source code for that utility; so it would have to be a binary built for your arch. If that is the case let us know and we can see what we can do.

**Comment by jpurple** [comment]
Thanks @csexton we will follow up on that question of Linux version soon. Really appreciate you reaching out.  On the way to answering that, can you help us to understand something...

We have installed and executed rbcom in order to see available commands, which include: advoff, advrate, bctype, connper, connwin, frameN, privacy, reboot, tlmratio, tlmtype. At a glance, none of these seem to be the commands which change the advertisement PDU. We are wondering if we want to approach this from a scriptable standpoint, can rbcom play a part for us, or do we need to be using gatttool directly.

Our scenario is that we want to be able to configure new beacons, which means changing the UUID, tx power, and other parameters.

Thanks

**Comment by jnebeker** [comment]
You won't need to use `gatttool`, everything can be configured over USB with `rbcom`.  The `frameN` command is used to configure a PDU frame on the RadBeacon.  There's five frames total (0-4) so, for example, to update the second PDU frame you use the `frame1` command.

To see what frames are currently configured on your 3.2.3 beacon, you can call:

 ```
# rbcom dump getinfo
```

This shows you the device info, settings, and the bytes for each frame.  Now, to command a new set of bytes to this frame (I'll use the same AltBeacon PDU from my earlier comment) use the following command (you have to pass in the 8 digit pin as well):

```
# rbcom frame1 0201061bff1801beac2f234454cf6d4a0fadf2f4911ba9ffa600010002be00 --pin 00000000
```

The hardest part is definitely building the proper PDU based on the beacon spec and identifiers, but there's plenty of good documentation out there for the different beacon standards.  You can also use the RadBeacon app (Android, iOS, macOS) to configure the beacon with the settings you want and then use `rbcom` to see what those corresponding frames/bytes look like as a way to decode it.

**Comment by jpurple** [comment]
Thank you @jnebeker we are currently working through this.  Your listing of the bytes UUID (bytes 10-25), Major (bytes 26-27), Minor (bytes 28-29), and TX Power (byte 30) shined the light on exactly how that info plays into things.  We now see exactly how they form the latter part of the beacon advertisement, and we feel confident about doing whatever we need to do there.

We are looking into the first portion:
`02 01 06 1b ff 18 01 be ac`

We've especially been examining the altbeacon spec here:
https://github.com/AltBeacon/spec

and this pdf which gives info on altbeacon, among other types:
http://www.emmicroelectronic.com/sites/default/files/public/products/datasheets/embc-mn01.pdf

Especially the PDF seems to give a clear picture of this first portion consisting of:

**ADVERTISEMENT LENGTH**
This field contains the length of the type and data portion of the Manufacturer Specific advertisement data
structure with a fixed definition of 0x1B.
**ADVERTISEMENT TYPE**
This field contains the Manufacturer Specific advertising data structure with a fixed definition of 0xFF.
**MANUFACTURE ID**
This field contains the beacon device manufacture’s company identifier code. The number is a little
endian representation of EM Microelectronic ID manufacture’s company code (90 = 0x005A), as
maintained by the Bluetooth SIG assigned numbers database.
**BEACON CODE**
This field contains the AltBeacon advertisement code. It is a big endian representation of the fixed value
0xBEAC.


This all appears to be manufacturer related and standard such as "beacon code."  Would it be correct to say that we could leave this value of "02 01 06 1b ff 18 01 be ac" unchanged as long as we are using Radius beacons as altbeacons? Thanks.

**Comment by jnebeker** [comment]
Yes that's exactly right @jpurple, all RadBeacons use the Radius Networks manufacturer ID so that entire first portion of the PDU will be unchanged.

**Comment by jpurple** [comment]
Thank you @jnebeker Your assistance gave us the right direction and now we are configuring beacons with rbcom

**Comment by jpurple** [comment]
(I had already sent this along with the previous one to @jnebeker Here, I am just isolating it out into its own message for the sake of housekeeping.)

@csexton Regarding Radius being open to compiling rbcom for Linux, we would be interested in that and would find it very useful in our workflow.  Our architecture would be Raspbian (a linux strain based on Debian optimized for Raspberry Pi hardware.)

We appreciate you seeing if this might be possible!  We understand it is something that will be looked into when time allows, and my team has asked me to inquire if this looks like something that might happen more like this week or next week, or if it could be something a little later on the calendar. 

Thanks!

**Comment by jpurple** [comment]
Follow up question...

in rbcom, when we type in rbcom without any parameters, we get the list of possible commands.  One command is:

`txpwr      <power>                Sets the transmit power, range 0-15 (15 is highest)`

since the tx is also part of the advertisement we have created

`TX Power (byte 30): -66`

we were wondering what is going on here?  What does it mean if we set, for example, 0, or 2, or 15 (converted to hex of course) in the advertisement?  How does that relate to actual values such as -66?

Also, if we set it in the advertisement, there seems to be no need to set it individually (such as `rbcom txpower 2` for example)... is that correct?  

If I use the Radbeacon app and slide the slider instead of smoothly going through sequentially through all digits, it skips some to form the following pattern which is 16 items long:
`-23,-21,-20,-18,-16,-14,-12,-11,-8,-7,-5,-4,-2,-1,0,3`

I am going to run a test and I have a feeling I will see that 0 to 15 corresponds to each of these.

**Comment by jpurple** [comment]
Follow up, yes our initial testing indicates those values correspond to 0 to 15. I won't erase the message until we finish our testing. Thanks!

**Comment by jnebeker** [comment]
That's right, the 0-15 are just arbitrary values used by the firmware and `rbcom`.  Those are presented with their dBm values in the RadBeacon app (-23, -21, etc.).  The transmit power (`txpower`) here is different from the power in the advertisement however.  The transmit power is the hardware setting on the BLE radio that controls the amount of energy the device uses to generate the signal.  A higher transmit power means the transmission will have a greater range, similarly you can lower the transmit power to decrease the range of the beacon signal.

The advertised power, used in the advertisement, is a calibration value that represents the average signal strength (in dBm) at a distance of 1 meter from the beacon.  This allows devices receiving the beacon advertisement to estimate the distance between them and the beacon.  You can measure this value using the calibration action in the RadBeacon app.

So it's true that these values are correlated, if you increase the transmit power setting then the signal strength at 1 meter will also increase, but they are distinct values and don't represent the exact same thing.
